var DEEvents;
(function (DEEvents) {
    DEEvents.OBJECT_SELECTED_EVENT = "OBJECT_SELECTED_EVENT";
    DEEvents.CONFIG_LOADED_EVENT = "CONFIG_LOADED_EVENT";
    DEEvents.LOAD_STATUS_EVENT = "LOAD_STATUS_EVENT";
    DEEvents.DESIGNER_CHANGED_EVENT = "DESIGNER_CHANGED_EVENT";
    DEEvents.DESIGN_READY_EVENT = "DESIGN_READY_EVENT";
    DEEvents.AUTH_EVENT = "AUTH_EVENT";
    DEEvents.OBJECT_DCLICK_EVENT = "OBJECT_DCLICK_EVENT";
    DEEvents.BACKGROUND_COLORIZE_PARSED_EVENT = "BACKGROUND_COLORIZE_PARSED_EVENT";
    DEEvents.VIEWPORT_UPDATE_EVENT = "VIEWPORT_UPDATE_EVENT";
})(DEEvents || (DEEvents = {}));